version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: seo_tools
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: LuksKebab59152&
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  clustering-kw:
    build: ./clustering-kw
    restart: always
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://monuser:LuksKebab59152&@postgres/seo_tools
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  ai-ranker:
    build: ./ai-ranker
    restart: always
    ports:
      - "8003:8000"  # ✅ Changement du port pour éviter le conflit
    environment:
      - DATABASE_URL=postgresql://monuser:LuksKebab59152&@postgres/seo_tools
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/seo-tools.conf:/etc/nginx/conf.d/seo-tools.conf
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - clustering-kw
      - ai-ranker
